ProgrammingAssignment3::Program
int ProgrammingAssignment3.Program.testCaseNumber
Referenced by ProgrammingAssignment3.Program.GetInputValueFromString, ProgrammingAssignment3.Program.Main.
List<string> ProgrammingAssignment3.Program.logMessages
Referenced by ProgrammingAssignment3.Program.Main.
static void ProgrammingAssignment3.Program.Main(string[] args)
Tests the Programming Assignment 3 classes
args command-line args
References ProgrammingAssignment3.Program.GetInputValueFromString, ProgrammingAssignment3.Program.HandleLogEvent, ProgrammingAssignment3.Program.InitializeTestCase, ProgrammingAssignment3.Program.logMessages, ProgrammingAssignment3.Program.testCaseNumber.
static void ProgrammingAssignment3.Program.GetInputValueFromString(string input)
Extracts the test case number from the given input string
input input string
References ProgrammingAssignment3.Program.testCaseNumber.
Referenced by ProgrammingAssignment3.Program.Main.
static void ProgrammingAssignment3.Program.HandleLogEvent(string message)
Handles the log event from the Debug mock
message message to log
Referenced by ProgrammingAssignment3.Program.Main.
static void ProgrammingAssignment3.Program.InitializeTestCase(Invoker invoker, Listener listener)
Initializes test case
Referenced by ProgrammingAssignment3.Program.Main.