Program
int Program.testCaseNumber
Referenced by GetInputValueFromString, Main.
List<string> Program.logMessages
Referenced by Main.
static void Program.Main(string[] args)
Tests the Programming Assignment 3 classes
args command-line args
References GetInputValueFromString, HandleLogEvent, InitializeTestCase, logMessages, testCaseNumber.
static void Program.GetInputValueFromString(string input)
Extracts the test case number from the given input string
input input string
References testCaseNumber.
Referenced by Main.
static void Program.HandleLogEvent(string message)
Handles the log event from the Debug mock
message message to log
Referenced by Main.
static void Program.InitializeTestCase(Invoker invoker, Listener listener)
Initializes test case
Referenced by Main.